Follow coreos/init PRs
- https://github.com/coreos/init/pull/94
- https://github.com/coreos/init/pull/95

diff --git a/oem/motdgen b/oem/motdgen
--- a/oem/motdgen
+++ b/oem/motdgen
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e
 
 # Copyright (c) 2014 The CoreOS Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style license that can be
@@ -9,36 +9,21 @@
 [ -e /etc/coreos/update.conf ] && source /etc/coreos/update.conf
 [ -e /etc/os-release ] && source /etc/os-release
 
-gen() {
-	mkdir -p /run/coreos
-	if [ -f /usr/share/oem/motd ]; then
-		cat /usr/share/oem/motd > /run/coreos/motd
-		echo -e "(${GROUP} ${VERSION})" >> /run/coreos/motd
-	else
-		echo -e "Core\033[38;5;45mO\033[38;5;206mS\033[39m (${GROUP})" > /run/coreos/motd
-	fi
+mkdir -p /run/coreos
+if [ -f /usr/share/oem/motd ]; then
+	cat /usr/share/oem/motd > /run/coreos/motd
+	echo -e "(${GROUP} ${VERSION})" >> /run/coreos/motd
+else
+	echo -e "Core\033[38;5;45mO\033[38;5;206mS\033[39m (${GROUP})" > /run/coreos/motd
+fi
 
-	systemctl is-active locksmithd > /dev/null
-	if [ $? -ne 0 ]; then
-		echo -e "Update Strategy: \033[31mNo Reboots\033[39m" >> /run/coreos/motd
-	fi
+if ! systemctl is-active locksmithd > /dev/null; then
+	echo -e "Update Strategy: \033[31mNo Reboots\033[39m" >> /run/coreos/motd
+fi
 
-	systemctl list-units --state=failed --no-legend > /run/coreos/motd-failed
-	count=$(cat /run/coreos/motd-failed | wc -l)
-	if [ ${count} -ne 0 ]; then
-		echo -e "Failed Units: \033[31m${count}\033[39m" >> /run/coreos/motd
-		cat /run/coreos/motd-failed | awk '{ print "  " $1 }' >> /run/coreos/motd
-	fi
-}
-
-gen
-
-dbus-send --system --dest=org.freedesktop.systemd1.Manager \
-	/org/freedesktop/systemd1 \
-	org.freedesktop.systemd1.Manager.Subscribe
-
-filter="type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'"
-dbus-monitor --system ${filter} |
-while read -r line; do
-	echo ${line} | egrep 'variant string "(failed|active)"' > /dev/null && gen
-done
+systemctl list-units --state=failed --no-legend > /run/coreos/motd-failed
+count=$(cat /run/coreos/motd-failed | wc -l)
+if [ ${count} -ne 0 ]; then
+	echo -e "Failed Units: \033[31m${count}\033[39m" >> /run/coreos/motd
+	cat /run/coreos/motd-failed | awk '{ print "  " $1 }' >> /run/coreos/motd
+fi
